### ISSUE TITLE
autosex broken

### ISSUE THREAD

**Issue by quervyloll** [nukiz/9hack-leak#4]
the 9hack autosex module is broken in this version, it doesnt let me have sex with jenny plz help me she doesnt take my emeraldaspsssssss

**Comment by AquaMinerale2b2t** [comment]
try taking a shower

**Comment by nukiz** [comment]
Try hitting the treadmill, this has been known to fix many issues

**Comment by quervyloll** [comment]
ive done both of these things and it still doesnt work plz help me
